//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiangShop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        public string checkID { get; set; }
        public string checkName { get; set; }
        public string branch { get; set; }
        public string userID { get; set; }
        public string billID { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual User User { get; set; }
    }
}
